### ISSUE TITLE
Too many integration steps needed within interval 

### ISSUE THREAD

**Issue by sk579** [Michalychforever/CLASS-PT#10]
Hello all,

I am using CLASS-PT with MontePython3 and the boss_full_shape data available [here](https://github.com/oliverphilcox/full_shape_likelihoods). During the run, I occasionally get the following error:

`Error in Class: background_init(L:655) :error in background_solve(ppr, pba);
=> background_solve(L:1596) :error in generic_integrator(background_derivs, tau_start, tau_end, pvecback_integration, &bpaw, ppr-> tol_background_integration, ppr->smallest_allowed_variation, &gi);
=> generic_integrator(L:127) :error; Too many integration steps needed within interval [528.247 : 593.7],
the system of equations is probably buggy or featuring a discontinuity`

While the error does not stop the run, I was curious about its origin, its effects on the quality of the chain, and how it may be fixed?

**Comment by oliverphilcox** [comment]
Hi Shubhum,

Thanks for the issue (and sorry for the slow reply). Great to hear you're interested in using the code. This sort of error comes from CLASS itself (note that it's occurring when CLASS computes the background expansion, rather than the extra non-linear computations done in CLASS-PT), and suggests that the input parameters are in some corner of parameter space where CLASS isn't very accurate. This can happen, for example, with very low omega_b. Generally, I wouldn't worry about this, since these problems should only happen at very strange points in parameter space which are usually highly suppressed in the likelihood anyway.

Cheers,
Oliver
