### ISSUE TITLE
CLASS-PT extension accounting for external P(k,z=0)

### ISSUE THREAD

**Issue by lontelis** [Michalychforever/CLASS-PT#2]
Dear Anton Chudaykin, Mikhail M. Ivanov, Marko Simonović, and anyone else who can help to resolve this issue,,

I am trying to implement the Leading Order and Next to Leading Order power spectrum, P_{LO}(k),P_{NLO} using the CLASS-PT and as an input to CLASS-PT the external linear power spectrum from flagship, i.e. P_L^{Flagship}(z=0,k), but as far as I understood:

1) the CLASS-PT and CLASS, have only modules from which one can use as an input an external power spectrum, but this external power spectrum should correspond to the primordial power spectrum. 
2) the CLASS-PT and CLASS (as well as CAMB) Einstein-Boltzmann (EB) solver, basically solve those EB equations assuming the input fiducial cosmological parameters and some guess for the initial power spectrum. This means that the output will be the linear power spectrum at redshift z,z=0, and also a corresponding, growth factor, D(z).  
3) Any FFTlog code, basically represents the P_L(z=0,k) in the form of a Series expansion with the base the k and some coefficients which are evaluated for the P_L(z=0,k), which leads to the output linear power spectrum \bar{P}_{L}(z=0,k). I guess this mean that the code solves EB for \bar{P}_L(k,z=0) and the growth factor D(z).

Given 1, 2, 3, how one can extend the CLASS-PT to calculate the P_{LO}(k) and P_{NLO}(k), using an external P_L(k,z=0) ?

Kind regards,
Pierros  (email: pntelis -at- cppm.in2p3.fr)

**Comment by oliverphilcox** [comment]
Hi Pierros,

Thanks for bringing this to our attention. We've made a change to CLASS-PT to accomodate this, as described at the bottom of this message. Please note the warning at the bottom.

Best regards,
Oliver

--------------------- 

The new change adds a new input parameter, 'Input Pk' to CLASS-PT. When this is set, CLASS-PT will set the linear power spectrum used in the 1-loop PT calculations to an externally provided CDM+baryon spectrum, rather than that estimated with CLASS's Boltzmann solver.

e.g. with the following snippet:

cosmo = Class ()
cosmo.set({...,
'Input Pk': '/home/input_pk.dat',
...
})
cosmo.compute()

CLASS-PT will read in the {k, P(k)} grid in '/home/input_pk.dat' and use this as the linear power spectrum, instead of the usual Boltzmann spectrum. These should be given in **1/Mpc** units, as a two-column ASCII file. The external input power spectrum should be computed at the same redshift as the desired output spectrum. By default this is a CDM+baryon spectrum.

**Note that the linear growth factors, D(z) & f(z), the Hubble parameter H(z), the angular diameter distance D_A(z), and the reduced Hubble constant h are used in the non-linear manipulations and will be set from the CLASS-PT parameters as usual.**

**Comment by Michalychforever** [comment]
If there's any need to use non-CLASS values for f(z), DA(z) and H(z) in the RSD/Alcock-Paczynski calculations, they can be input by hand around line 1000 in `source/nonlinear_pt.c' ,

pnlpt->growthf[i_z] = ...
pnlpt->Dratio_array[i_z] = ...
pnlpt->hratio_array[i_z] = ...

where i_z is the index of the requested redshifts array, specified by *z_pk*
